name: Monkey Interpreter
on:
  push:
    branches:
      - main

jobs:
  build_monkey:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout and make the files available to the workflow
        uses: actions/checkout@v4

      - name: Setup Go v1.24.2
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.2"
          cache: true

      - name: Install dependencies
        run: |
          go get .

      - name: Compile it and generate a WASM output
        run: GOOS=js GOARCH=wasm go build -o interpreter.wasm

      - name: Upload the WASM Binary to the artifact
        uses: actions/upload-artifact@v4
        with:
          name: interpreter-wasm
          path: interpreter.wasm

  build_playground:
    needs: build_monkey
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./editor

    steps:
      - name: Checkout and make the files available to the workflow
        uses: actions/checkout@v4
        with:
          sparse-checkout: editor
          sparse-checkout-cone-mode: false

      - name: Setup Node JS v22.15.0
        uses: actions/setup-node@v4
        with:
          node-version: "22.15.0"

      - name: Download WASM binary from the artifact
        uses: actions/download-artifact@v4
        with:
          name: interpreter-wasm

      - name: Move WASM binary to the static folder of the editor codebase
        run: |
          cd ..
          mv interpreter.wasm editor/static/wasm

      - run: npm ci

      - run: npm run build

      - name: Upload the Svelte build to the artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: editor/build

  deploy:
    needs: build_playground
    runs-on: ubuntu-latest

    permissions:
       contents: read
       deployments: write

    steps:
      - name: Download the Svelte build from the artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy build --project-name=monkey-lang
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
